import { Inter } from "next/font/google";
import "@styles/globals.css";

import NextAuthProvider from "@components/providers/NextAuthProvider";
import { ThemeProvider } from "@components/providers/ThemeProvider";
import { ModeToggle } from "@components/fixedComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-[#121212]`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextAuthProvider>
            <main>{children}</main>

            <div className="fixed z-[1000000000000000000] right-3 bottom-3">
              <ModeToggle border={false} />
            </div>
          </NextAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
