import { Inter } from "next/font/google";
import "@styles/globals.css";

import Provider from "@providers/NextAuthProvider";
import NavbarComponent from "@components/NavbarComponent";
import { CartProvider } from "@Context/CartContext";
import FooterComponent from "@components/FooterComponent";
import { Toaster } from "@components/ui/toaster";
import { ThemeProvider } from "@providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <CartProvider>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Provider>
              <NavbarComponent />
              <main>{children}</main>

              <Toaster />
              <FooterComponent />
            </Provider>
          </ThemeProvider>
        </body>
      </CartProvider>
    </html>
  );
}
